[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://47.120.73.69/ffd-p4-api/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "http://47.120.73.69/ffd-p4-api/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
